// Question Imposter Game - Question Pairs
// Same topic, opposite twist — answers can overlap but inconsistencies show through discussion

const QUESTION_CATEGORIES = {
    twistAndTurn: {
        name: "Twist & Turn",
        icon: "🔄",
        questions: [
            { real: "What is your favorite way to relax?", imposter: "What is your least favorite way to relax?" },
            { real: "What food could you eat every day?", imposter: "What food would you never eat again?" },
            { real: "What skill would you love to master?", imposter: "What skill do you think is overrated?" },
            { real: "What place would you love to visit?", imposter: "What place would you avoid visiting?" },
            { real: "What makes a good friend?", imposter: "What makes a bad friend?" },
            { real: "What motivates you the most?", imposter: "What distracts you the most?" },
            { real: "What habit improves your day?", imposter: "What habit ruins your day?" },
            { real: "What job would you enjoy doing?", imposter: "What job would you hate doing?" },
            { real: "What is your strongest trait?", imposter: "What is your weakest trait?" },
            { real: "What app do you use the most?", imposter: "What app do you avoid using?" },
            { real: "What movie genre do you love?", imposter: "What movie genre bores you?" },
            { real: "What time of day are you most productive?", imposter: "What time of day are you most tired?" },
            { real: "What subject did you enjoy in school?", imposter: "What subject did you struggle with?" },
            { real: "What purchase made you happy?", imposter: "What purchase did you regret?" },
            { real: "What weather do you like?", imposter: "What weather do you dislike?" },
            { real: "What activity energizes you?", imposter: "What activity drains you?" },
            { real: "What makes a great vacation?", imposter: "What ruins a vacation?" },
            { real: "What talent do you admire?", imposter: "What talent do you not care about?" },
            { real: "What helps you focus?", imposter: "What breaks your focus?" },
            { real: "What is a perfect weekend?", imposter: "What is a boring weekend?" },
            { real: "What music helps your mood?", imposter: "What music annoys you?" },
            { real: "What hobby would you try?", imposter: "What hobby would you quit quickly?" },
            { real: "What makes work enjoyable?", imposter: "What makes work unbearable?" },
            { real: "What quality makes someone memorable?", imposter: "What quality makes someone forgettable?" },
            { real: "What is your comfort food?", imposter: "What food makes you uncomfortable?" },
            { real: "What improves a conversation?", imposter: "What kills a conversation?" },
            { real: "What makes you laugh?", imposter: "What makes you cringe?" },
            { real: "What would you teach others?", imposter: "What would you struggle to teach?" },
            { real: "What is worth waiting for?", imposter: "What is not worth waiting for?" },
            { real: "What makes a home cozy?", imposter: "What makes a home uncomfortable?" },
            { real: "What do you enjoy spending money on?", imposter: "What do you hate spending money on?" },
            { real: "What makes mornings better?", imposter: "What makes mornings worse?" },
            { real: "What makes someone trustworthy?", imposter: "What makes someone suspicious?" },
            { real: "What makes a good leader?", imposter: "What makes a bad leader?" },
            { real: "What improves your mood instantly?", imposter: "What worsens your mood instantly?" },
            { real: "What makes a party fun?", imposter: "What makes a party awkward?" },
            { real: "What makes a great gift?", imposter: "What makes a terrible gift?" },
            { real: "What is easy for you to learn?", imposter: "What is hard for you to learn?" },
            { real: "What do you enjoy cooking?", imposter: "What do you avoid cooking?" },
            { real: "What makes a good day?", imposter: "What makes a bad day?" },
            { real: "What makes you feel confident?", imposter: "What makes you feel insecure?" },
            { real: "What is your ideal workspace?", imposter: "What is your worst workspace?" },
            { real: "What makes a good decision?", imposter: "What makes a bad decision?" },
            { real: "What makes travel enjoyable?", imposter: "What makes travel stressful?" },
            { real: "What do you enjoy talking about?", imposter: "What do you avoid talking about?" },
            { real: "What makes someone interesting?", imposter: "What makes someone boring?" },
            { real: "What makes a good habit?", imposter: "What makes a bad habit?" },
            { real: "What makes you excited?", imposter: "What makes you nervous?" },
            { real: "What is a good surprise?", imposter: "What is a bad surprise?" },
            { real: "What improves productivity?", imposter: "What hurts productivity?" },
            { real: "What makes you proud?", imposter: "What makes you embarrassed?" },
            { real: "What makes you feel accomplished?", imposter: "What makes you feel stuck?" },
            { real: "What makes you feel relaxed?", imposter: "What makes you feel tense?" },
            { real: "What is easy to forgive?", imposter: "What is hard to forgive?" },
            { real: "What improves teamwork?", imposter: "What damages teamwork?" },
            { real: "What improves sleep?", imposter: "What ruins sleep?" },
            { real: "What improves friendships?", imposter: "What damages friendships?" },
            { real: "What improves learning?", imposter: "What blocks learning?" },
            { real: "What improves creativity?", imposter: "What blocks creativity?" },
            { real: "What improves communication?", imposter: "What breaks communication?" },
            { real: "What makes life easier?", imposter: "What makes life harder?" },
            { real: "What is fun to repeat?", imposter: "What gets boring quickly?" },
            { real: "What risk is worth taking?", imposter: "What risk is not worth taking?" },
            { real: "What advice would you give?", imposter: "What advice would you ignore?" },
            { real: "What do you value most?", imposter: "What do you value least?" },
            { real: "What is worth learning?", imposter: "What is pointless to learn?" },
            { real: "What improves health?", imposter: "What hurts health?" },
            { real: "What improves happiness?", imposter: "What hurts happiness?" },
            { real: "What improves focus?", imposter: "What hurts focus?" },
            { real: "What improves motivation?", imposter: "What kills motivation?" },
            { real: "What improves energy?", imposter: "What drains energy?" },
            { real: "What improves confidence?", imposter: "What damages confidence?" },
            { real: "What improves relationships?", imposter: "What damages relationships?" },
            { real: "What improves habits?", imposter: "What destroys habits?" },
            { real: "What improves discipline?", imposter: "What weakens discipline?" },
            { real: "What improves memory?", imposter: "What makes you forgetful?" },
            { real: "What improves performance?", imposter: "What hurts performance?" },
            { real: "What improves learning speed?", imposter: "What slows learning?" },
            { real: "What improves problem solving?", imposter: "What blocks problem solving?" },
            { real: "What improves decision making?", imposter: "What leads to bad decisions?" },
            { real: "What makes you comfortable?", imposter: "What makes you uncomfortable?" },
            { real: "What makes you feel safe?", imposter: "What makes you uneasy?" },
            { real: "What makes you optimistic?", imposter: "What makes you pessimistic?" },
            { real: "What makes you patient?", imposter: "What makes you impatient?" },
            { real: "What makes you curious?", imposter: "What makes you uninterested?" },
            { real: "What makes something enjoyable?", imposter: "What makes something annoying?" },
            { real: "What makes something memorable?", imposter: "What makes something forgettable?" },
            { real: "What makes someone likable?", imposter: "What makes someone unlikable?" },
            { real: "What makes something valuable?", imposter: "What makes something useless?" },
            { real: "What makes something exciting?", imposter: "What makes something dull?" },
            { real: "What makes you say yes?", imposter: "What makes you say no?" },
            { real: "What makes you stay?", imposter: "What makes you leave?" },
            { real: "What makes you trust?", imposter: "What makes you doubt?" },
            { real: "What makes you agree?", imposter: "What makes you disagree?" },
            { real: "What makes you commit?", imposter: "What makes you hesitate?" },
            { real: "What makes you try harder?", imposter: "What makes you give up?" },
            { real: "What makes you feel prepared?", imposter: "What makes you feel unprepared?" },
            { real: "What makes you feel successful?", imposter: "What makes you feel unsuccessful?" },
            { real: "What makes you feel motivated?", imposter: "What makes you feel demotivated?" },
            { real: "What makes something a good experience?", imposter: "What makes something a bad experience?" },
            // Spicy Set 2 (Pairs 101–200)
            { real: "What is your biggest green flag in a person?", imposter: "What is your biggest red flag in a person?" },
            { real: "What is something you secretly enjoy?", imposter: "What is something you secretly dislike?" },
            { real: "What is your guilty pleasure?", imposter: "What is your guilty annoyance?" },
            { real: "What is something you pretend to understand?", imposter: "What is something you genuinely understand well?" },
            { real: "What is something you are proud of?", imposter: "What is something you hide about yourself?" },
            { real: "What is your most attractive trait?", imposter: "What is your most awkward trait?" },
            { real: "What makes someone instantly charming?", imposter: "What makes someone instantly irritating?" },
            { real: "What is something you find irresistible?", imposter: "What is something you find unbearable?" },
            { real: "What is your most controversial opinion?", imposter: "What is your safest opinion?" },
            { real: "What is something you judge people for?", imposter: "What is something people judge you for?" },
            { real: "What is your worst habit?", imposter: "What is your best habit?" },
            { real: "What is something you overspend on?", imposter: "What is something you refuse to spend on?" },
            { real: "What is something you exaggerate about yourself?", imposter: "What is something you downplay about yourself?" },
            { real: "What is something you would brag about?", imposter: "What is something you would never admit?" },
            { real: "What is your most impressive skill?", imposter: "What skill do you wish you had?" },
            { real: "What is something you are bad at but enjoy?", imposter: "What is something you are good at but dislike?" },
            { real: "What is something that makes you jealous?", imposter: "What is something that makes you feel superior?" },
            { real: "What is your most irrational fear?", imposter: "What is your most irrational confidence?" },
            { real: "What is something you find attractive?", imposter: "What is something you find unattractive?" },
            { real: "What is something you pretend to like?", imposter: "What is something you openly dislike?" },
            { real: "What makes someone intimidating?", imposter: "What makes someone unimpressive?" },
            { real: "What is something you crave often?", imposter: "What is something you avoid often?" },
            { real: "What is your most dramatic reaction ever?", imposter: "What is your calmest reaction ever?" },
            { real: "What is your most impulsive decision?", imposter: "What is your most calculated decision?" },
            { real: "What is something you would never do again?", imposter: "What is something you would happily repeat?" },
            { real: "What is your most questionable choice?", imposter: "What is your smartest choice?" },
            { real: "What is something you envy?", imposter: "What is something you pity?" },
            { real: "What is something you find addictive?", imposter: "What is something you find boring quickly?" },
            { real: "What is something that stresses you out?", imposter: "What is something that excites you?" },
            { real: "What is your comfort zone?", imposter: "What is your danger zone?" },
            { real: "What is something you love attention for?", imposter: "What is something you hate attention for?" },
            { real: "What makes someone unforgettable?", imposter: "What makes someone forgettable?" },
            { real: "What is your most charming lie?", imposter: "What is your most honest truth?" },
            { real: "What is something you fake confidence in?", imposter: "What is something you are truly confident in?" },
            { real: "What is your most useless talent?", imposter: "What is your most useful weakness?" },
            { real: "What is something you are weirdly good at?", imposter: "What is something you are weirdly bad at?" },
            { real: "What makes someone attractive beyond looks?", imposter: "What ruins attraction instantly?" },
            { real: "What is your most dramatic thought?", imposter: "What is your most logical thought?" },
            { real: "What is something you romanticize?", imposter: "What is something you criticize?" },
            { real: "What is something you would defend fiercely?", imposter: "What is something you would abandon quickly?" },
            { real: "What is your most dangerous personality trait?", imposter: "What is your safest personality trait?" },
            { real: "What is something you are too stubborn about?", imposter: "What is something you give up on easily?" },
            { real: "What is something that makes you feel powerful?", imposter: "What is something that makes you feel powerless?" },
            { real: "What is your most impressive flex?", imposter: "What is your most embarrassing anti-flex?" },
            { real: "What is something you could talk about forever?", imposter: "What is something you avoid discussing?" },
            { real: "What is something you love arguing about?", imposter: "What is something not worth arguing about?" },
            { real: "What is your most chaotic moment?", imposter: "What is your most controlled moment?" },
            { real: "What is your most confident decision?", imposter: "What is your most doubtful decision?" },
            { real: "What is something you find seductive?", imposter: "What is something you find awkward?" },
            { real: "What is your most magnetic quality?", imposter: "What is your most repelling quality?" },
            { real: "What is something you pretend not to care about?", imposter: "What is something you genuinely do not care about?" },
            { real: "What is something you crave validation for?", imposter: "What is something you ignore validation for?" },
            { real: "What is something that boosts your ego?", imposter: "What is something that bruises your ego?" },
            { real: "What is your most unreasonable expectation?", imposter: "What is your most reasonable expectation?" },
            { real: "What is your most dramatic assumption?", imposter: "What is your most rational assumption?" },
            { real: "What is your most attractive confidence?", imposter: "What is your most visible insecurity?" },
            { real: "What is something you enjoy judging?", imposter: "What is something you hate being judged for?" },
            { real: "What is your most confident social move?", imposter: "What is your most awkward social move?" },
            { real: "What is something you secretly compete about?", imposter: "What is something you openly compete about?" },
            { real: "What is something that makes you feel irresistible?", imposter: "What is something that makes you feel invisible?" },
            { real: "What is your boldest opinion?", imposter: "What is your most boring opinion?" },
            { real: "What is your most charming flaw?", imposter: "What is your most annoying flaw?" },
            { real: "What is something you love being complimented on?", imposter: "What is something you are tired of being complimented on?" },
            { real: "What is something you wish people noticed about you?", imposter: "What is something you wish people ignored about you?" },
            { real: "What is something you fake liking socially?", imposter: "What is something you genuinely like socially?" },
            { real: "What is your most confident exaggeration?", imposter: "What is your most honest understatement?" },
            { real: "What is your most charming defense mechanism?", imposter: "What is your most obvious defense mechanism?" },
            { real: "What is something that instantly attracts you?", imposter: "What is something that instantly repels you?" },
            { real: "What is your most confident vibe?", imposter: "What is your most insecure vibe?" },
            { real: "What is something you would confidently recommend?", imposter: "What is something you would warn people about?" },
            { real: "What is something you take pride in doing well?", imposter: "What is something you struggle to do well?" },
            { real: "What is your most confident life choice?", imposter: "What is your most doubtful life choice?" },
            { real: "What is something you love being known for?", imposter: "What is something you fear being known for?" },
            { real: "What is your most charming social trait?", imposter: "What is your most awkward social trait?" },
            { real: "What is something you find effortlessly cool?", imposter: "What is something you find painfully uncool?" },
            { real: "What is something you admire openly?", imposter: "What is something you criticize openly?" },
            { real: "What is something you love taking risks on?", imposter: "What is something you never risk?" },
            { real: "What is your most confident assumption about yourself?", imposter: "What is your most critical assumption about yourself?" },
            { real: "What is your most charming first impression move?", imposter: "What is your most awkward first impression move?" },
            { real: "What is something you enjoy showing off?", imposter: "What is something you avoid showing?" },
            { real: "What is your most attractive energy?", imposter: "What is your most intimidating energy?" },
            { real: "What is your most confident conversation topic?", imposter: "What is your most uncomfortable conversation topic?" },
            { real: "What is something you find instantly engaging?", imposter: "What is something you find instantly draining?" },
            { real: "What is your most confident reaction style?", imposter: "What is your most defensive reaction style?" },
            { real: "What is something you love being asked about?", imposter: "What is something you dread being asked about?" },
            { real: "What is your most charming confidence trick?", imposter: "What is your most obvious insecurity tell?" },
            { real: "What is something you feel superior at?", imposter: "What is something you feel inferior at?" },
            { real: "What is your most confident personality label?", imposter: "What is your most unfair personality label?" },
            { real: "What is something you enjoy exaggerating emotionally?", imposter: "What is something you underreact to emotionally?" },
            { real: "What is something you love dramatically?", imposter: "What is something you dislike dramatically?" },
            { real: "What is your most confident social skill?", imposter: "What social skill do you lack?" },
            { real: "What is something you naturally excel at?", imposter: "What is something you fake being good at?" },
            { real: "What is your most confident aesthetic choice?", imposter: "What aesthetic choice do you regret?" },
            { real: "What is something you proudly indulge in?", imposter: "What is something you reluctantly tolerate?" },
            { real: "What is your most confident opinion about people?", imposter: "What is your most skeptical opinion about people?" },
            { real: "What is something you love attention for?", imposter: "What is something you avoid attention for?" },
            { real: "What is your most confident comfort behavior?", imposter: "What is your most obvious stress behavior?" },
            { real: "What is something you enjoy being admired for?", imposter: "What is something you fear being criticized for?" },
            { real: "What is your most confident instinct?", imposter: "What instinct do you distrust?" },
            { real: "What is something that makes you feel effortlessly confident?", imposter: "What is something that makes you feel instantly self-conscious?" }
        ]
    }
};

function getRandomQuestion(categoryKey) {
    const cat = QUESTION_CATEGORIES[categoryKey];
    if (!cat || !cat.questions?.length) return null;
    const idx = Math.floor(Math.random() * cat.questions.length);
    return cat.questions[idx];
}

if (typeof globalThis !== 'undefined') {
    globalThis.QUESTION_CATEGORIES = QUESTION_CATEGORIES;
    globalThis.getRandomQuestion = getRandomQuestion;
}

// Export for use in the game
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { QUESTION_CATEGORIES, getRandomQuestion };
}
